### PR TITLE
Implement gif search function

### PR DESCRIPTION
**Pull request by LL835**
Hi Laura,

Here's what I've got for the gif searching part of the project. Let me know what you think!

The main changes are:
* When the user submits the form, a new output container is created. The output container is styled like the hero but has different class names.
* The search function tries to get a gif related to the search term but if it there isn't one it gets a random gif instead.

Not sure if this is a problem but the same search term gets the same gif every time e.g. searching "cat" will get the same cat gif. Happy to try handling this if needed.

### CODE REVIEW

**Comment by LauraK0** [comment]
Thanks Derek, I see what you mean about it returning the same gif.
I guess it's because you're always taking the first index of the returned response?
````
const gifURL = gifSearchResults.data[0].images.downsized.url;
`````
I think it's fine, but if you had the time, we could get the number of responses and generate a random number with that, then call that as the index?

Also the output gif's size varies and can sometimes distort the size of the output box - is it possible to constrain this?

**Comment by LL835** [comment]
Thanks, Laura. Yes, you're right about the index. Should be a quick fix.

I noticed the output gif issue too but don't know the best way to fix it. Setting the gifs to fixed widths/heights distort the aspect ratio. Could just have a fixed-size container but leave the size of the gif alone/use `object-fit` somehow? Will look into it today.

**Comment by LL835** [comment]
Ok so I made it get a random related gif instead of the first available one with: 
```
const NoOfResults = gifSearchResults.data.length;
const randomIndex = Math.floor(Math.random() * NoOfResults);
const gifURL = gifSearchResults.data[randomIndex].images.downsized.url;
```
The problem with the gif's size should also be fixed but lmk if something's off.

**Review by LauraK0 — APPROVED** [review]
Awesome, its working really nicely!

**Pull request merged**
