### PR TITLE
heading and search box html and css added

### PR DESCRIPTION
**Pull request by LauraK0**
- added html and css for heading and search box
- added media queries for different screen sizes
- also added some fonts that I think work well

Let me know your thoughts, thanks!
Relates #3

### CODE REVIEW

**Review by LL835 — APPROVED** [review]
Wow looks amazing. Just a tiny suggestion to change `width: 750px` to `max-width: 1000px` in `<header>` so that it aligns with the container below it. What do you think?

**Comment by LauraK0** [comment]
Hey Derek, thanks. I did have a look at doing that but the content felt a bit stretched. Would it be better to reduce the container below to max-width:750?

Screenshot 2022-10-16 at 12 52 23

Note sure if the image links works ^

**Comment by LL835** [comment]
Now that you mention it, I agree it's a bit wide. How about somewhere in the middle - `max-width: 850px` for both? I think the text is easier to read with a little more space.

**Comment by LauraK0** [comment]
850 sounds good. I've added another commit. Do you know if I need to open another pull request? Or can both be merged from here?

**Comment by LL835** [comment]
Thanks, Laura - looking pretty cool imo. I think it can be merged from here.

**Pull request merged**
